-- Lernzeit: private Gruppen mit maximal zehn Mitgliedern
-- Diese Datei einmal vollständig im Supabase SQL Editor ausführen.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 30),
  appearance_theme text not null default 'sunset' check (appearance_theme in ('sunset', 'noir')),
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 40),
  invite_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  invite_enabled boolean not null default true,
  invite_expires_at timestamptz,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  max_members smallint not null default 10 check (max_members between 2 and 10),
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  group_id uuid references public.groups(id) on delete set null,
  entry_date date not null,
  category text not null check (category in ('studium', 'arbeit', 'persoenlich', 'sonstiges')),
  minutes integer not null check (minutes between 1 and 1439),
  elapsed_minutes integer not null check (elapsed_minutes between minutes and 1439),
  topic text not null default '' check (char_length(topic) <= 80),
  visibility text not null default 'private' check (visibility in ('group', 'admins', 'private')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_join_requests (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references public.profiles(id) on delete set null,
  primary key (group_id, user_id)
);

create table if not exists public.learning_goals (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  weekly_minutes integer not null default 600 check (weekly_minutes between 30 and 10080),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_audit_log (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.groups(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists entries_user_date_idx on public.entries(user_id, entry_date desc);
create index if not exists group_members_group_idx on public.group_members(group_id);
create index if not exists group_join_requests_group_idx on public.group_join_requests(group_id, status, created_at desc);
create index if not exists group_audit_log_group_idx on public.group_audit_log(group_id, created_at desc);

-- Erlaubt ein erneutes Ausführen dieses Schemas bei bereits angelegten Projekten.
alter table public.profiles add column if not exists appearance_theme text not null default 'sunset';
alter table public.profiles drop constraint if exists profiles_appearance_theme_check;
alter table public.profiles
  add constraint profiles_appearance_theme_check check (appearance_theme in ('sunset', 'noir'));

alter table public.groups drop constraint if exists groups_max_members_check;
alter table public.groups alter column max_members set default 10;
alter table public.groups add column if not exists invite_enabled boolean not null default true;
alter table public.groups add column if not exists invite_expires_at timestamptz;
alter table public.groups
  add constraint groups_max_members_check check (max_members between 2 and 10);

alter table public.group_members drop constraint if exists group_members_user_id_key;
alter table public.group_members drop constraint if exists group_members_role_check;
alter table public.group_members
  add constraint group_members_role_check check (role in ('owner', 'admin', 'member'));

alter table public.entries
  add column if not exists group_id uuid references public.groups(id) on delete set null;
alter table public.entries add column if not exists updated_at timestamptz not null default now();
alter table public.entries drop constraint if exists entries_visibility_check;
alter table public.entries
  add constraint entries_visibility_check check (visibility in ('group', 'admins', 'private'));
update public.entries entry
set group_id = membership.group_id
from public.group_members membership
where entry.group_id is null
  and membership.user_id = entry.user_id
  and 1 = (
    select count(*)
    from public.group_members memberships
    where memberships.user_id = entry.user_id
  );
create index if not exists entries_group_date_idx on public.entries(group_id, entry_date desc);

create or replace function public.is_group_member(target_group_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.group_members
    where group_id = target_group_id and user_id = (select auth.uid())
  );
$$;

create or replace function public.shares_group_with(other_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.group_members mine
    join public.group_members theirs on theirs.group_id = mine.group_id
    where mine.user_id = (select auth.uid()) and theirs.user_id = other_user_id
  );
$$;

create or replace function public.is_group_admin(target_group_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.group_members
    where group_id = target_group_id
      and user_id = (select auth.uid())
      and role in ('owner', 'admin')
  );
$$;

create or replace function public.can_view_join_requester(other_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.group_join_requests request
    join public.group_members administrator on administrator.group_id = request.group_id
    where request.user_id = other_user_id
      and request.status = 'pending'
      and administrator.user_id = (select auth.uid())
      and administrator.role in ('owner', 'admin')
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.write_group_audit(
  target_group_id uuid,
  action_name text,
  target_user_id uuid default null,
  action_details jsonb default '{}'::jsonb
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.group_audit_log (group_id, actor_id, action, target_user_id, details)
  values (
    target_group_id,
    (select auth.uid()),
    action_name,
    target_user_id,
    coalesce(action_details, '{}'::jsonb)
    || jsonb_build_object(
      'actorName', coalesce((select display_name from public.profiles where id = (select auth.uid())), 'Unbekannt')
    )
    || case
      when target_user_id is null then '{}'::jsonb
      else jsonb_build_object(
        'targetName', coalesce((select display_name from public.profiles where id = target_user_id), 'Unbekannt')
      )
    end
  );
$$;

create or replace function public.create_private_group(group_name text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_group_id uuid;
  cleaned_name text := trim(group_name);
begin
  if (select auth.uid()) is null then
    raise exception 'Du musst angemeldet sein.';
  end if;
  if char_length(cleaned_name) < 2 or char_length(cleaned_name) > 40 then
    raise exception 'Der Gruppenname muss 2 bis 40 Zeichen lang sein.';
  end if;
  insert into public.groups (name, owner_id)
  values (cleaned_name, (select auth.uid()))
  returning id into new_group_id;

  insert into public.group_members (group_id, user_id, role)
  values (new_group_id, (select auth.uid()), 'owner');
  perform public.write_group_audit(new_group_id, 'group_created');
  return new_group_id;
end;
$$;

create or replace function public.join_private_group(invitation_code text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_group public.groups%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'Du musst angemeldet sein.';
  end if;
  select * into target_group
  from public.groups
  where invite_code = upper(trim(invitation_code))
  for update;

  if target_group.id is null then
    raise exception 'Der Einladungs-Code ist ungültig.';
  end if;
  if not target_group.invite_enabled then
    raise exception 'Einladungen für diese Gruppe sind deaktiviert.';
  end if;
  if target_group.invite_expires_at is not null and target_group.invite_expires_at < now() then
    raise exception 'Dieser Einladungs-Code ist abgelaufen.';
  end if;

  if exists (
    select 1 from public.group_members
    where group_id = target_group.id and user_id = (select auth.uid())
  ) then
    raise exception 'Du bist bereits Mitglied dieser Gruppe.';
  end if;

  insert into public.group_join_requests (group_id, user_id, status, created_at, decided_at, decided_by)
  values (target_group.id, (select auth.uid()), 'pending', now(), null, null)
  on conflict (group_id, user_id) do update
  set status = 'pending', created_at = now(), decided_at = null, decided_by = null;
  perform public.write_group_audit(target_group.id, 'join_requested', (select auth.uid()));
  return target_group.id;
end;
$$;

create or replace function public.get_group_invite_code(target_group_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result text;
begin
  select groups.invite_code into result
  from public.groups
  join public.group_members on group_members.group_id = groups.id
  where groups.id = target_group_id
    and group_members.user_id = (select auth.uid())
    and group_members.role in ('owner', 'admin');

  if result is null then
    raise exception 'Nur Admins dürfen den Einladungs-Code sehen.';
  end if;
  return result;
end;
$$;

create or replace function public.get_group_admin_settings(target_group_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen die Einladungseinstellungen sehen.';
  end if;
  select jsonb_build_object(
    'inviteCode', invite_code,
    'inviteEnabled', invite_enabled,
    'inviteExpiresAt', invite_expires_at
  ) into result
  from public.groups where id = target_group_id;
  return result;
end;
$$;

create or replace function public.set_group_member_role(target_group_id uuid, target_user_id uuid, new_role text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_role text;
begin
  if new_role is null or new_role not in ('admin', 'member') then
    raise exception 'Diese Rolle ist nicht erlaubt.';
  end if;

  if not exists (
    select 1 from public.group_members
    where group_id = target_group_id
      and user_id = (select auth.uid())
      and role = 'owner'
  ) then
    raise exception 'Nur der Hauptadmin darf Rollen vergeben.';
  end if;

  select role into target_role
  from public.group_members
  where group_id = target_group_id and user_id = target_user_id;

  if target_role is null then
    raise exception 'Dieses Konto gehört nicht zu deiner Gruppe.';
  end if;
  if target_role = 'owner' then
    raise exception 'Die Rolle des Hauptadmins kann nicht geändert werden.';
  end if;

  update public.group_members
  set role = new_role
  where group_id = target_group_id and user_id = target_user_id;
  perform public.write_group_audit(
    target_group_id,
    case when new_role = 'admin' then 'admin_granted' else 'admin_revoked' end,
    target_user_id
  );
end;
$$;

create or replace function public.remove_group_member(target_group_id uuid, target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  managers_role text;
  target_role text;
begin
  select role into managers_role
  from public.group_members
  where group_id = target_group_id
    and user_id = (select auth.uid())
    and role in ('owner', 'admin');

  if managers_role is null then
    raise exception 'Du darfst keine Mitglieder entfernen.';
  end if;

  select role into target_role
  from public.group_members
  where group_id = target_group_id and user_id = target_user_id;

  if target_role is null then
    raise exception 'Dieses Konto gehört nicht zu deiner Gruppe.';
  end if;
  if target_role = 'owner' or (managers_role = 'admin' and target_role = 'admin') then
    raise exception 'Dieses Mitglied darfst du nicht entfernen.';
  end if;

  update public.entries
  set group_id = null
  where group_id = target_group_id and user_id = target_user_id;

  delete from public.group_members
  where group_id = target_group_id and user_id = target_user_id;
  perform public.write_group_audit(target_group_id, 'member_removed', target_user_id);
end;
$$;

create or replace function public.set_group_max_members(target_group_id uuid, new_max_members smallint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_size integer;
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen die Gruppengröße ändern.';
  end if;
  if new_max_members is null or new_max_members < 2 or new_max_members > 10 then
    raise exception 'Die Gruppengröße muss zwischen 2 und 10 liegen.';
  end if;

  perform 1 from public.groups
  where id = target_group_id
  for update;

  select count(*) into current_size
  from public.group_members
  where group_id = target_group_id;

  if new_max_members < current_size then
    raise exception 'Die Gruppe hat bereits mehr Mitglieder als diese Platzanzahl.';
  end if;

  update public.groups
  set max_members = new_max_members
  where id = target_group_id;
  perform public.write_group_audit(
    target_group_id,
    'capacity_changed',
    null,
    jsonb_build_object('maxMembers', new_max_members)
  );
end;
$$;

create or replace function public.set_group_invite_settings(
  target_group_id uuid,
  invitations_enabled boolean,
  expires_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen Einladungen verwalten.';
  end if;
  if expires_at is not null and expires_at <= now() then
    raise exception 'Das Ablaufdatum muss in der Zukunft liegen.';
  end if;
  update public.groups
  set invite_enabled = coalesce(invitations_enabled, false), invite_expires_at = expires_at
  where id = target_group_id;
  perform public.write_group_audit(
    target_group_id,
    'invite_settings_changed',
    null,
    jsonb_build_object('enabled', coalesce(invitations_enabled, false), 'expiresAt', expires_at)
  );
end;
$$;

create or replace function public.rotate_group_invite_code(target_group_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_code text := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen den Einladungs-Code erneuern.';
  end if;
  update public.groups set invite_code = new_code where id = target_group_id;
  perform public.write_group_audit(target_group_id, 'invite_code_rotated');
  return new_code;
end;
$$;

create or replace function public.decide_group_join_request(
  target_group_id uuid,
  target_user_id uuid,
  approve_request boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_size integer;
  maximum_size integer;
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen Beitrittsanfragen bearbeiten.';
  end if;
  if not exists (
    select 1 from public.group_join_requests
    where group_id = target_group_id and user_id = target_user_id and status = 'pending'
  ) then
    raise exception 'Diese Beitrittsanfrage ist nicht mehr offen.';
  end if;

  if coalesce(approve_request, false) then
    select max_members into maximum_size from public.groups where id = target_group_id for update;
    select count(*) into current_size from public.group_members where group_id = target_group_id;
    if current_size >= maximum_size then
      raise exception 'Diese Gruppe hat ihre maximale Mitgliederzahl erreicht.';
    end if;
    insert into public.group_members (group_id, user_id, role)
    values (target_group_id, target_user_id, 'member')
    on conflict (group_id, user_id) do nothing;
  end if;

  update public.group_join_requests
  set status = case when coalesce(approve_request, false) then 'approved' else 'rejected' end,
      decided_at = now(), decided_by = (select auth.uid())
  where group_id = target_group_id and user_id = target_user_id;
  perform public.write_group_audit(
    target_group_id,
    case when coalesce(approve_request, false) then 'join_approved' else 'join_rejected' end,
    target_user_id
  );
end;
$$;

create or replace function public.rename_group(target_group_id uuid, new_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  cleaned_name text := trim(new_name);
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen die Gruppe umbenennen.';
  end if;
  if char_length(cleaned_name) < 2 or char_length(cleaned_name) > 40 then
    raise exception 'Der Gruppenname muss 2 bis 40 Zeichen lang sein.';
  end if;
  update public.groups set name = cleaned_name where id = target_group_id;
  perform public.write_group_audit(target_group_id, 'group_renamed', null, jsonb_build_object('name', cleaned_name));
end;
$$;

create or replace function public.transfer_group_ownership(target_group_id uuid, target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.group_members
    where group_id = target_group_id and user_id = (select auth.uid()) and role = 'owner'
  ) then
    raise exception 'Nur der Hauptadmin darf den Besitz übertragen.';
  end if;
  if target_user_id = (select auth.uid()) or not exists (
    select 1 from public.group_members where group_id = target_group_id and user_id = target_user_id
  ) then
    raise exception 'Wähle ein anderes Mitglied dieser Gruppe.';
  end if;
  update public.group_members set role = 'admin'
  where group_id = target_group_id and user_id = (select auth.uid());
  update public.group_members set role = 'owner'
  where group_id = target_group_id and user_id = target_user_id;
  update public.groups set owner_id = target_user_id where id = target_group_id;
  perform public.write_group_audit(target_group_id, 'ownership_transferred', target_user_id);
end;
$$;

create or replace function public.leave_group(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_role text;
begin
  select role into current_role from public.group_members
  where group_id = target_group_id and user_id = (select auth.uid());
  if current_role is null then
    raise exception 'Du bist kein Mitglied dieser Gruppe.';
  end if;
  if current_role = 'owner' then
    raise exception 'Übertrage zuerst den Hauptadmin oder lösche die Gruppe.';
  end if;
  update public.entries set group_id = null
  where group_id = target_group_id and user_id = (select auth.uid());
  perform public.write_group_audit(target_group_id, 'member_left', (select auth.uid()));
  delete from public.group_members
  where group_id = target_group_id and user_id = (select auth.uid());
end;
$$;

create or replace function public.delete_group(target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.group_members
    where group_id = target_group_id and user_id = (select auth.uid()) and role = 'owner'
  ) then
    raise exception 'Nur der Hauptadmin darf die Gruppe löschen.';
  end if;
  delete from public.groups where id = target_group_id;
end;
$$;

create or replace function public.delete_entry(target_entry_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_entry public.entries%rowtype;
begin
  select * into target_entry from public.entries where id = target_entry_id;
  if target_entry.id is null then raise exception 'Eintrag nicht gefunden.'; end if;
  if target_entry.user_id <> (select auth.uid()) and not (
    target_entry.visibility <> 'private' and public.is_group_admin(target_entry.group_id)
  ) then
    raise exception 'Du darfst diesen Eintrag nicht löschen.';
  end if;
  delete from public.entries where id = target_entry_id;
  if target_entry.user_id <> (select auth.uid()) then
    perform public.write_group_audit(target_entry.group_id, 'entry_deleted_by_admin', target_entry.user_id,
      jsonb_build_object('entryId', target_entry.id, 'topic', target_entry.topic));
  end if;
end;
$$;

create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (select 1 from public.groups where owner_id = (select auth.uid())) then
    raise exception 'Übertrage oder lösche zuerst deine eigenen Gruppen.';
  end if;
  delete from auth.users where id = (select auth.uid());
end;
$$;

alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.entries enable row level security;
alter table public.group_join_requests enable row level security;
alter table public.learning_goals enable row level security;
alter table public.group_audit_log enable row level security;

drop policy if exists "group profiles are visible" on public.profiles;
create policy "group profiles are visible" on public.profiles
  for select to authenticated
  using (
    id = (select auth.uid())
    or public.shares_group_with(id)
    or public.can_view_join_requester(id)
  );

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

drop policy if exists "members view their group" on public.groups;
create policy "members view their group" on public.groups
  for select to authenticated
  using (public.is_group_member(id));

drop policy if exists "members view memberships" on public.group_members;
create policy "members view memberships" on public.group_members
  for select to authenticated
  using (public.is_group_member(group_id));

drop policy if exists "visible entries for group" on public.entries;
create policy "visible entries for group" on public.entries
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or (visibility = 'group' and public.is_group_member(group_id))
    or (visibility = 'admins' and public.is_group_admin(group_id))
  );

drop policy if exists "users create own entries" on public.entries;
create policy "users create own entries" on public.entries
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and (group_id is null or public.is_group_member(group_id))
  );

drop policy if exists "users update own entries" on public.entries;
create policy "users update own entries" on public.entries
  for update to authenticated
  using (
    user_id = (select auth.uid())
    or (visibility <> 'private' and public.is_group_admin(group_id))
  )
  with check (
    (user_id = (select auth.uid()) and (group_id is null or public.is_group_member(group_id)))
    or (visibility <> 'private' and public.is_group_admin(group_id))
  );

drop policy if exists "users delete own entries" on public.entries;
create policy "users delete own entries" on public.entries
  for delete to authenticated
  using (
    user_id = (select auth.uid())
    or (visibility <> 'private' and public.is_group_admin(group_id))
  );

drop policy if exists "requests visible to requester and admins" on public.group_join_requests;
create policy "requests visible to requester and admins" on public.group_join_requests
  for select to authenticated
  using (user_id = (select auth.uid()) or public.is_group_admin(group_id));

drop policy if exists "users manage own goal" on public.learning_goals;
create policy "users manage own goal" on public.learning_goals
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "admins view group audit" on public.group_audit_log;
create policy "admins view group audit" on public.group_audit_log
  for select to authenticated
  using (public.is_group_admin(group_id));

revoke all on public.profiles, public.groups, public.group_members, public.entries,
  public.group_join_requests, public.learning_goals, public.group_audit_log from anon;
grant select, update on public.profiles to authenticated;
revoke select on public.groups from authenticated;
grant select (id, name, owner_id, max_members, created_at) on public.groups to authenticated;
grant select on public.group_members to authenticated;
grant select, insert, update, delete on public.entries to authenticated;
grant select on public.group_join_requests, public.group_audit_log to authenticated;
grant select, insert, update, delete on public.learning_goals to authenticated;

revoke all on function public.is_group_member(uuid) from public;
revoke all on function public.shares_group_with(uuid) from public;
revoke all on function public.is_group_admin(uuid) from public;
revoke all on function public.can_view_join_requester(uuid) from public;
revoke all on function public.write_group_audit(uuid, text, uuid, jsonb) from public;
revoke all on function public.create_private_group(text) from public;
revoke all on function public.join_private_group(text) from public;
revoke all on function public.get_group_invite_code(uuid) from public;
revoke all on function public.get_group_admin_settings(uuid) from public;
revoke all on function public.set_group_member_role(uuid, uuid, text) from public;
revoke all on function public.remove_group_member(uuid, uuid) from public;
revoke all on function public.set_group_max_members(uuid, smallint) from public;
revoke all on function public.set_group_invite_settings(uuid, boolean, timestamptz) from public;
revoke all on function public.rotate_group_invite_code(uuid) from public;
revoke all on function public.decide_group_join_request(uuid, uuid, boolean) from public;
revoke all on function public.rename_group(uuid, text) from public;
revoke all on function public.transfer_group_ownership(uuid, uuid) from public;
revoke all on function public.leave_group(uuid) from public;
revoke all on function public.delete_group(uuid) from public;
revoke all on function public.delete_entry(uuid) from public;
revoke all on function public.delete_own_account() from public;
grant execute on function public.is_group_member(uuid) to authenticated;
grant execute on function public.shares_group_with(uuid) to authenticated;
grant execute on function public.is_group_admin(uuid) to authenticated;
grant execute on function public.can_view_join_requester(uuid) to authenticated;
grant execute on function public.create_private_group(text) to authenticated;
grant execute on function public.join_private_group(text) to authenticated;
grant execute on function public.get_group_invite_code(uuid) to authenticated;
grant execute on function public.get_group_admin_settings(uuid) to authenticated;
grant execute on function public.set_group_member_role(uuid, uuid, text) to authenticated;
grant execute on function public.remove_group_member(uuid, uuid) to authenticated;
grant execute on function public.set_group_max_members(uuid, smallint) to authenticated;
grant execute on function public.set_group_invite_settings(uuid, boolean, timestamptz) to authenticated;
grant execute on function public.rotate_group_invite_code(uuid) to authenticated;
grant execute on function public.decide_group_join_request(uuid, uuid, boolean) to authenticated;
grant execute on function public.rename_group(uuid, text) to authenticated;
grant execute on function public.transfer_group_ownership(uuid, uuid) to authenticated;
grant execute on function public.leave_group(uuid) to authenticated;
grant execute on function public.delete_group(uuid) to authenticated;
grant execute on function public.delete_entry(uuid) to authenticated;
grant execute on function public.delete_own_account() to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'entries'
  ) then
    alter publication supabase_realtime add table public.entries;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'group_members'
  ) then
    alter publication supabase_realtime add table public.group_members;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'groups'
  ) then
    alter publication supabase_realtime add table public.groups;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'group_join_requests'
  ) then
    alter publication supabase_realtime add table public.group_join_requests;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'group_audit_log'
  ) then
    alter publication supabase_realtime add table public.group_audit_log;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'learning_goals'
  ) then
    alter publication supabase_realtime add table public.learning_goals;
  end if;
end $$;

-- Erweiterung: Mehrfach-Gruppenzuordnung, Lösch-Wiederherstellung und Gruppenziele.
-- Ein Lernzeiteintrag kann mehreren Gruppen zugeordnet werden.

create table if not exists public.entry_groups (
  entry_id uuid not null references public.entries(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (entry_id, group_id)
);

create table if not exists public.group_weekly_goals (
  group_id uuid primary key references public.groups(id) on delete cascade,
  weekly_minutes integer not null check (weekly_minutes between 30 and 100800),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

alter table public.entries add column if not exists deleted_at timestamptz;
alter table public.entries add column if not exists elapsed_minutes integer;
update public.entries set elapsed_minutes = minutes where elapsed_minutes is null;
alter table public.entries alter column elapsed_minutes set not null;
alter table public.entries drop constraint if exists entries_elapsed_minutes_check;
alter table public.entries
  add constraint entries_elapsed_minutes_check check (elapsed_minutes between minutes and 1439);

insert into public.entry_groups (entry_id, group_id)
select id, group_id from public.entries where group_id is not null
on conflict do nothing;

-- Zusammengehörige Datensätze der bisherigen Mehrfachauswahl werden zu einem
-- Eintrag vereinigt; alle Gruppenzuordnungen bleiben erhalten.
do $$
declare
  duplicate record;
begin
  for duplicate in
    select id, canonical_id
    from (
      select
        id,
        first_value(id) over (
          partition by user_id, created_at
          order by id
        ) as canonical_id
      from public.entries
    ) ranked
    where id <> canonical_id
  loop
    insert into public.entry_groups (entry_id, group_id)
    select duplicate.canonical_id, group_id
    from public.entry_groups
    where entry_id = duplicate.id
    on conflict do nothing;
    delete from public.entries where id = duplicate.id;
  end loop;
end $$;

create index if not exists entry_groups_group_idx on public.entry_groups(group_id, entry_id);
create index if not exists entries_deleted_idx on public.entries(deleted_at) where deleted_at is null;

create or replace function public.can_view_entry(target_entry_id uuid, entry_visibility text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.entry_groups association
    join public.group_members membership on membership.group_id = association.group_id
    where association.entry_id = target_entry_id
      and membership.user_id = (select auth.uid())
      and (
        entry_visibility = 'group'
        or (entry_visibility = 'admins' and membership.role in ('owner', 'admin'))
      )
  );
$$;

create or replace function public.can_manage_entry(target_entry_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.entry_groups association
    where association.entry_id = target_entry_id
      and public.is_group_admin(association.group_id)
  );
$$;

drop function if exists public.save_learning_entry(uuid, date, text, integer, text, text, uuid[]);

create or replace function public.save_learning_entry(
  target_entry_id uuid,
  target_entry_date date,
  target_category text,
  target_minutes integer,
  target_elapsed_minutes integer,
  target_topic text,
  target_visibility text,
  target_group_ids uuid[] default '{}'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  cleaned_group_ids uuid[] := coalesce(target_group_ids, '{}');
  cleaned_visibility text := target_visibility;
begin
  if (select auth.uid()) is null then raise exception 'Du musst angemeldet sein.'; end if;
  if target_entry_id is null then raise exception 'Eintrag-ID fehlt.'; end if;
  if target_elapsed_minutes is null or target_elapsed_minutes < target_minutes or target_elapsed_minutes > 1439 then
    raise exception 'Die gesamte Sitzzeit muss mindestens der tatsächlichen Lernzeit entsprechen.';
  end if;
  if exists (
    select 1 from public.entries
    where id = target_entry_id and user_id <> (select auth.uid())
  ) then raise exception 'Du darfst diesen Eintrag nicht bearbeiten.'; end if;
  if exists (
    select 1 from unnest(cleaned_group_ids) selected_group_id
    where not public.is_group_member(selected_group_id)
  ) then raise exception 'Du bist nicht Mitglied jeder ausgewählten Gruppe.'; end if;
  if cardinality(cleaned_group_ids) = 0 then cleaned_visibility := 'private'; end if;

  insert into public.entries (
    id, user_id, group_id, entry_date, category, minutes, elapsed_minutes, topic, visibility, deleted_at, updated_at
  ) values (
    target_entry_id,
    (select auth.uid()),
    cleaned_group_ids[1],
    target_entry_date,
    target_category,
    target_minutes,
    target_elapsed_minutes,
    coalesce(trim(target_topic), ''),
    cleaned_visibility,
    null,
    now()
  )
  on conflict (id) do update set
    group_id = excluded.group_id,
    entry_date = excluded.entry_date,
    category = excluded.category,
    minutes = excluded.minutes,
    elapsed_minutes = excluded.elapsed_minutes,
    topic = excluded.topic,
    visibility = excluded.visibility,
    deleted_at = null,
    updated_at = now()
  where public.entries.user_id = (select auth.uid());

  delete from public.entry_groups where entry_id = target_entry_id;
  insert into public.entry_groups (entry_id, group_id)
  select target_entry_id, selected_group_id
  from (select distinct unnest(cleaned_group_ids) as selected_group_id) selected
  where selected_group_id is not null;
  return target_entry_id;
end;
$$;

create or replace function public.delete_entry(target_entry_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_entry public.entries%rowtype;
begin
  select * into target_entry from public.entries where id = target_entry_id;
  if target_entry.id is null then raise exception 'Eintrag nicht gefunden.'; end if;
  if target_entry.user_id <> (select auth.uid()) and not (
    target_entry.visibility <> 'private'
    and exists (
      select 1 from public.entry_groups association
      where association.entry_id = target_entry.id
        and public.is_group_admin(association.group_id)
    )
  ) then raise exception 'Du darfst diesen Eintrag nicht löschen.'; end if;

  update public.entries set deleted_at = now(), updated_at = now() where id = target_entry_id;
  if target_entry.user_id <> (select auth.uid()) then
    perform public.write_group_audit(
      (select group_id from public.entry_groups where entry_id = target_entry.id and public.is_group_admin(group_id) limit 1),
      'entry_deleted_by_admin',
      target_entry.user_id,
      jsonb_build_object('entryId', target_entry.id, 'topic', target_entry.topic)
    );
  end if;
end;
$$;

create or replace function public.restore_own_entry(target_entry_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.entries
  set deleted_at = null, updated_at = now()
  where id = target_entry_id and user_id = (select auth.uid());
$$;

create or replace function public.remove_entry_from_group(target_entry_id uuid, target_group_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_entry public.entries%rowtype;
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Du darfst diesen Gruppeneintrag nicht entfernen.';
  end if;
  select * into target_entry from public.entries where id = target_entry_id;
  if target_entry.id is null or target_entry.visibility = 'private' then
    raise exception 'Eintrag nicht gefunden.';
  end if;
  delete from public.entry_groups
  where entry_id = target_entry_id and group_id = target_group_id;
  if not found then raise exception 'Dieser Eintrag gehört nicht zu deiner Gruppe.'; end if;
  update public.entries
  set group_id = (select group_id from public.entry_groups where entry_id = target_entry_id limit 1),
      updated_at = now()
  where id = target_entry_id;
  perform public.write_group_audit(
    target_group_id,
    'entry_deleted_by_admin',
    target_entry.user_id,
    jsonb_build_object('entryId', target_entry.id, 'topic', target_entry.topic)
  );
end;
$$;

create or replace function public.set_group_weekly_goal(target_group_id uuid, target_minutes integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_group_admin(target_group_id) then
    raise exception 'Nur Admins dürfen das Gruppenziel ändern.';
  end if;
  if target_minutes is null or target_minutes < 30 or target_minutes > 100800 then
    raise exception 'Das Gruppenziel muss zwischen 30 Minuten und 1.680 Stunden liegen.';
  end if;
  insert into public.group_weekly_goals (group_id, weekly_minutes, updated_at, updated_by)
  values (target_group_id, target_minutes, now(), (select auth.uid()))
  on conflict (group_id) do update set
    weekly_minutes = excluded.weekly_minutes,
    updated_at = now(),
    updated_by = (select auth.uid());
  perform public.write_group_audit(
    target_group_id,
    'group_goal_changed',
    null,
    jsonb_build_object('weeklyMinutes', target_minutes)
  );
end;
$$;

create or replace function public.remove_departed_member_entry_groups()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.entry_groups association
  using public.entries entry
  where association.entry_id = entry.id
    and association.group_id = old.group_id
    and entry.user_id = old.user_id;
  update public.entries
  set group_id = null
  where group_id = old.group_id and user_id = old.user_id;
  return old;
end;
$$;

drop trigger if exists remove_departed_member_entry_groups on public.group_members;
create trigger remove_departed_member_entry_groups
  after delete on public.group_members
  for each row execute procedure public.remove_departed_member_entry_groups();

alter table public.entry_groups enable row level security;
alter table public.group_weekly_goals enable row level security;

drop policy if exists "visible entries for group" on public.entries;
create policy "visible entries for group" on public.entries
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or (deleted_at is null and public.can_view_entry(id, visibility))
  );

drop policy if exists "users update own entries" on public.entries;
create policy "users update own entries" on public.entries
  for update to authenticated
  using (
    user_id = (select auth.uid())
    or (visibility <> 'private' and public.can_manage_entry(id))
  )
  with check (
    user_id = (select auth.uid())
    or (visibility <> 'private' and public.can_manage_entry(id))
  );

drop policy if exists "entry associations are visible" on public.entry_groups;
create policy "entry associations are visible" on public.entry_groups
  for select to authenticated
  using (
    public.is_group_member(group_id)
    or exists (
      select 1 from public.entries entry
      where entry.id = entry_id and entry.user_id = (select auth.uid())
    )
  );

drop policy if exists "members view group goals" on public.group_weekly_goals;
create policy "members view group goals" on public.group_weekly_goals
  for select to authenticated
  using (public.is_group_member(group_id));

revoke all on public.entry_groups, public.group_weekly_goals from anon;
revoke all on public.entry_groups, public.group_weekly_goals from authenticated;
grant select on public.entry_groups, public.group_weekly_goals to authenticated;

revoke all on function public.can_view_entry(uuid, text) from public;
revoke all on function public.can_manage_entry(uuid) from public;
revoke all on function public.save_learning_entry(uuid, date, text, integer, integer, text, text, uuid[]) from public;
revoke all on function public.restore_own_entry(uuid) from public;
revoke all on function public.remove_entry_from_group(uuid, uuid) from public;
revoke all on function public.set_group_weekly_goal(uuid, integer) from public;
revoke all on function public.remove_departed_member_entry_groups() from public;
grant execute on function public.can_view_entry(uuid, text) to authenticated;
grant execute on function public.can_manage_entry(uuid) to authenticated;
grant execute on function public.save_learning_entry(uuid, date, text, integer, integer, text, text, uuid[]) to authenticated;
grant execute on function public.restore_own_entry(uuid) to authenticated;
grant execute on function public.remove_entry_from_group(uuid, uuid) to authenticated;
grant execute on function public.set_group_weekly_goal(uuid, integer) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'group_weekly_goals'
  ) then
    alter publication supabase_realtime add table public.group_weekly_goals;
  end if;
end $$;
